### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Skywalkcat428** [Skywalkcat428/protospace-30613#2]
自身のProtoSpaceのURL（本番環境(Heroku)のURL）
https://protospace-30613.herokuapp.com/

**Comment by airraid714** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
未ログインの状態でURLを直接入力すると、新規投稿画面に遷移できてしまう。
（未ログイン状態でhttps://protospace-30613.herokuapp.com/prototypes/new入力）

→実装条件の「未ログイン時は、特定のページ以外には遷移できず、ログインページにリダイレクトされる」になるように修正しましょう！

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Skywalkcat428** [comment]
修正確認お願い致します。
https://protospace-30613.herokuapp.com/

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
前回の修正点が確認できました。ありがとうございます。
一点、修正点をあげさせていただきますので、こちら対応をお願い致します。

[修正箇所]
・詳細ページリンクをクリックすると、プロトタイプが削除できる。削除が完了すると、トップページへ遷移する。
→こちらですがプロトタイプの削除が確認できず、また添付画像にあるエラー画面が表示されてしまいます。上記要件を満たすように修正をお願い致します。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

<img width="553" alt="スクリーンショット 2020-10-19 9 01 43" src="https://user-images.githubusercontent.com/57244739/96389385-3f7b5980-11ea-11eb-91b0-09acec8e792b.png">

**Comment by Skywalkcat428** [comment]
再修正確認お願い致します。
https://protospace-30613.herokuapp.com/

**Comment by vesper1102609** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by Skywalkcat428** [comment]
ありがとうございました。
